name:                hs-reddit-image-browser
version:             0.1.0.0
github:              "rmanne/hs-reddit-image-browser"
license:             BSD3
author:              "Rahul Manne"
maintainer:          "rahul_manne@hotmail.com"
copyright:           "2018 Rahul Manne"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rmanne/hs-reddit-image-browser#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- mtl
- directory
- text
- reddit
- api-builder
- cereal
- regex-pcre
- http-conduit
- filepath
- process
- wreq
- http-client
- aeson
- lens
- time
- aria2c-rpc
- ffmpeg-light
- sdl2
- monad-loops
- transformers
- vector
- unordered-containers
- yaml
- data-default
- extra
- JuicyPixels
- JuicyPixels-extra
- bytestring-to-vector

default-extensions:
- LambdaCase
- OverloadedStrings
- TupleSections
- MultiWayIf
- NamedFieldPuns
- RecordWildCards
- FlexibleContexts
- ScopedTypeVariables

library:
  source-dirs: src

executables:
  rib:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -main-is Main
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wpartial-fields
    - -Wmissing-home-modules
    - -Widentities
    - -Wredundant-constraints
    - -Wcpp-undef
    - -Wmissing-export-lists
    - -Wmissing-import-lists
    - -Wmonomorphism-restriction
    - -Wmissing-local-signatures
    - -Wmissed-specialisations
    - -Werror
    # https://medium.com/mercury-bank/enable-all-the-warnings-a0517bc081c3
    dependencies:
    - hs-reddit-image-browser
